### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by zxc1212sc1000** [Milomilo0320/A-Semi-automatic-Annotation-Software-for-Scene-Graph#4]
Traceback (most recent call last):
  File "main.py", line 2022, in <module>
    scene_graph.render("anewsg.gv", view=False)
  File "D:\Softwares\python 3.6.7\lib\site-packages\graphviz\rendering.py", line 83, in render
    rendered = self._render(*args, **kwargs)
  File "D:\Softwares\python 3.6.7\lib\site-packages\graphviz\backend\rendering.py", line 62, in render
    execute.run_check(cmd, capture_output=True, cwd=cwd, quiet=quiet)
  File "D:\Softwares\python 3.6.7\lib\site-packages\graphviz\backend\execute.py", line 88, in run_check
    proc = subprocess.run(cmd, **kwargs)
  File "D:\Softwares\python 3.6.7\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Softwares\python 3.6.7\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Softwares\python 3.6.7\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "D:\Softwares\python 3.6.7\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by zxc1212sc1000** [comment]
It's need python>=3.8
